import type { Metadata } from "next";
import { Header } from "@/components/shared/Header";
import { Footer } from "@/components/shared/Footer";
import { JSX } from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const tenants = new Map([["www.aisleguide.app", [Header, Footer]]]);

export const dynamic = "force-dynamic";

export default async function TenantLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ tenant: string }>;
}>) {
    const { tenant } = await params;

    const Sections = tenants.get(tenant);
    const Header = Sections?.at(0) ?? null;
    const Footer = Sections?.at(1) ?? null;

    return (
        <html lang="en">
            <body className={`antialiased`}>
                {Header !== null && <Header />}
                {children}
                {Footer !== null && <Footer />}
            </body>
        </html>
    );
}
