import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import "devicon/devicon.min.css"
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} antialiased h-screen bg-background px-4 lg:px-0`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
